<?php 

return 
[
    "common_yes" => 'Tak',
    "common_no" => 'Nie',
    "common_active" => 'Aktywny',
    "common_deactive" => 'Nieaktywny',
    "common_delete" => 'Usuń',
    "common_edit" => 'Edytuj',
    "common_submit_save" => 'Zapisz',
    "common_submit_back" => 'Wróć',
    "common_select_default_value" => '- wybierz',
    "common_header_position" => 'Pozycja',
    "common_position_change" => 'Zmień pozycje',
    "common_add" => 'Dodaj',
    "common_upload" => 'Wgraj',
    
    "common_arteh_upper" => 'ARTEH',
    "common_arteh_full_text" => 'ARTEH Agencja Interaktywna',
    "common_cms_upper" => 'CMS',
    "common_all_right_reserved" => 'Wszelkie prawa zastrzeżone',
    
    'sidebar_management' => 'Zarządzanie',
    "sidebar_moules" => 'Moduły',
    "sidebar_menu" => 'Menu',
    "sidebar_partials" => 'Pojedyncze elementy',
    "sidebar_configuration" => 'Konfiguracja',
    "sidebar_users" => 'Użytkownicy',
    "sidebar_modules" => 'Moduły',
    "sidebar_account" => 'Moje konto',
    "sidebar_logout" => 'Wyloguj',
    "sidebar_dashboard" => "Strona główna",
    
    "container_fluid_dashboard" => "Strona główna",
    "container_fluid_contact" => "Kontakt",
    

    "page_account_title" => "Moje konto",
    
    "page_dashboard_title" => "Dashboard",
    
    
    "page_errors_404_title" => "404",
    "page_errors_404_description" => "Strona o podanym adresie nie istnieje",
    
    
    
    
    "page_404_title" => "Nie odnaleziono strony",
    
    
    // ----------------------
    
    "module_form" => "Formularz kontaktowy",
    "module_gallery" => "Galeria",
    "module_html" => "Html",
    "module_simple_gallery" => "Pojedyncza galeria",
    "module_news" => "Aktualności",
    "module_meta_tags" => "Dane meta",
    "module_maintenance" => "Tryb konserwacji",
    "module_contact" => "Dane kontaktowe",
    
    // ----------------------
    
    "page_login_lead" => "Podaj login i hasło",
    "page_login_placeholder_login" => "Login",
    "page_login_placeholder_password" => "Hasło",
    "page_login_button_submit" => "Zaloguj",
    
    "page_configuration_edit_modules_header" => "Domyślna konfiguracja modułów",
    "page_configuration_edit_form_header" => "Formularz kontaktowy",
    "page_configuration_edit_form_mail" => "Adres e-mail",
    "page_configuration_edit_gallery_header" => "Galeria",
    "page_configuration_edit_html_header" => "Html",
    "page_configuration_edit_simple_gallery_header" => "Pojedyncza galeria",
    "page_configuration_edit_news_header" => "Aktualności",
    "page_configuration_edit_meta_tags_header" => "Dane meta",
    "page_configuration_edit_meta_tags_title" => "Tytuł strony",
    "page_configuration_edit_meta_tags_description" => "Opis strony",
    "page_configuration_edit_meta_tags_key_words" => "Słowa kluczowe",
    "page_configuration_edit_form_header" => "Formularz kontaktowy",
    "page_configuration_edit_contact_header" => "Kontakt",
    "page_configuration_edit_contact_company_first_line" => "Nazwa firmy",
    "page_configuration_edit_contact_company_second_line" => "Adres firmy",
    "page_configuration_edit_contact_person_name" => "Osoba do kontaktu",
    "page_configuration_edit_contact_person_phone" => "Telefon",
    "page_configuration_edit_contact_person_mail" => "Adres e-mail",
    "page_configuration_edit_maintenance_header" => "Tryb konserwacji",
    "page_configuration_edit_maintenance_active" => "Włączyć stronę serwisową",
    "page_configuration_edit_maintenance_html" => "Treść strony serwisowej",
    
    "page_partials_header_name" => "Nazwa",
    "page_partials_header_module_translate" => "Moduł",
    "page_partials_header_symbol" => "Symbol",
    "page_partials_header_created" => "Utworzono",
    "page_partials_header_modified" => "Zmodyfikowano",
    "page_partials_edit_name" => "Nazwa",
    "page_partials_edit_symbol" => "Symbol",
    "page_partials_edit_module" => "Moduł",
    
    "page_menu_header_name" => "Nazwa",
    "page_menu_header_type" => "Typ",
    "page_menu_header_active" => "Aktywny",
    "page_menu_header_target" => "Cel",
    "page_menu_header_created" => "Utworzono",
    "page_menu_header_modified" => "Zmodyfikowano",
    "page_menu_edit_name" => "Nazwa",
    "page_menu_edit_parent_id" => "Ścierzka menu",
    "page_menu_edit_parent_id_empty" => "Menu główne",
    "page_menu_edit_symbol" => "Symbol",
    "page_menu_edit_url" => "Url",
    "page_menu_edit_link" => "Link",
    "page_menu_edit_type" => "Typ",
    "page_menu_edit_target" => "Cel",
    "page_menu_edit_active" => "Aktywny",
    "page_menu_edit_created" => "Utworzono",
    "page_menu_edit_modified" => "Zmodyfikowano",
    "page_menu_manage_name" => "Nazwa",
    "page_menu_manage_parent_path" => "Ścierzka menu",
    "page_menu_manage_module" => "Dodaj moduł",
    "page_menu_manage_module_added_to_menu" => "Moduły dodane do elementu menu",
    
    "page_modules_header_name" => "Nazwa",
    "page_modules_header_type" => "Typ",
    "page_modules_header_file" => "Plik",
    "page_modules_header_active" => "Aktywny",
    "page_modules_header_created" => "Utworzono",
    "page_modules_header_modified" => "Zmodyfikowano",
    "page_modules_edit_name" => "Nazwa",
    "page_modules_edit_type" => "Typ",
    "page_modules_edit_file" => "Plik",
    "page_modules_edit_active" => "Aktywny",
    "page_modules_edit_created" => "Utworzono",
    "page_modules_edit_modified" => "Zmodyfikowano",
    
    "page_users_header_login" => "Login",
    "page_users_header_name" => "Nazwa",
    "page_users_header_acl" => "Typ",
    "page_users_header_active" => "Aktywny",
    "page_users_header_created" => "Utworzono",
    "page_users_header_modified" => "Zmodyfikowano",
    "page_users_edit_login" => "Login",
    "page_users_edit_password" => "Hasło",
    "page_users_edit_password_text" => "Pozostaw puste jeśli nie chcesz zmieniać hasła",
    "page_users_edit_name" => "Nazwa",
    "page_users_edit_acl" => "Typ",
    "page_users_edit_active" => "Aktywny",
    "page_users_edit_created" => "Utworzono",
    "page_users_edit_modified" => "Zmodyfikowano",
    
    "page_account_edit_login" => "Login",
    "page_account_edit_password" => "Hasło",
    "page_account_edit_password_text" => "Pozostaw puste jeśli nie chcesz zmieniać hasła",
    "page_account_edit_name"  => "Nazwa",
    "page_account_edit_avatar" => "Zdjęcie",
    "page_account_edit_active" => "Aktywny",
    "page_account_edit_acl" => "Typ",
    "page_account_edit_created" => "Utworzono",
    "page_account_edit_modified" => "Zmodyfikowano",
    
    //----------------------
    
    "breadcrumb_account_edit" => "Moje konto",
    "breadcrumb_home" => "Strona głóna",
    "breadcrumb_dashboard_index" => "Strona głóna",
    "breadcrumb_configuration_edit" => "Konfiguracja",
    "breadcrumb_menu_index" => "Zarządzanie menu",
    "breadcrumb_menu_add" => "Dodaj menu",
    "breadcrumb_menu_edit" => "Edytuj menu",
    "breadcrumb_menu_manage" => "Zarządzaj elementem menu",
    "breadcrumb_modules_index" => "Moduły",
    "breadcrumb_modules_add" => "Dodaj moduł",
    "breadcrumb_modules_edit" => "Edytuj moduł",
    "breadcrumb_users_index" => "Użytkownicy",
    "breadcrumb_users_add" => "Dodaj użytkownika",
    "breadcrumb_users_edit" => "Edytuj użytkownika",
    "breadcrumb_partials_index" => "Pojedyncze elementy",
    "breadcrumb_partials_add" => "Dodaj element",
    "breadcrumb_partials_edit" => "Edytuj element",
    "breadcrumb_contact_index" => "Kontakt",
    
    "title_account_edit" => "Moje konto",
    "title_dashboard_index" => "Strona głóna",
    "title_configuration_edit" => "Konfiguracja",
    "title_menu_index" => "Zarządzanie menu",
    "title_menu_add" => "Dodaj menu",
    "title_menu_edit" => "Edytuj menu",
    "title_menu_manage" => "Zarządzaj elementem menu",
    "title_modules_index" => "Moduły",
    "title_modules_add" => "Dodaj moduł",
    "title_modules_edit" => "Edytuj moduł",
    "title_users_index" => "Użytkownicy",
    "title_users_add" => "Dodaj użytkownika",
    "title_users_edit" => "Edytuj użytkownika",
    "title_partials_index" => "Pojedyncze elementy",
    "title_partials_add" => "Dodaj element",
    "title_partials_edit" => "Edytuj element",
    "title_contact_index" => "Kontakt",
    
    "common_button_activate" => "Aktywuj",
    "common_button_deactivate" => "Deaktywuj",
    "common_button_edit" => "Edytuj",
    "common_button_delete" => "Usuń",
    "common_button_menu" => "Menu",
    "common_button_manage" => "Zarządzaj",
    
    "dictionary_common_active_0" => 'Nieaktywny',
    "dictionary_common_active_1" => 'Aktywny',
    "dictionary_common_acl_0" => 'Brak',
    "dictionary_common_acl_1" => 'Użytkownik',
    "dictionary_common_acl_5" => 'Administrator',
    "dictionary_common_acl_9" => 'Supervisor',
    "dictionary_common_menu_1" => 'Strona z treścią',
    "dictionary_common_menu_2" => 'Rodzic',
    "dictionary_common_menu_3" => 'Rodzic z treścią',
    "dictionary_common_menu_9" => 'Link do strony',
    "dictionary_common_target_0" => 'To samo okno',
    "dictionary_common_target_1" => 'Nowe okno',
    "dictionary_common_module_static" => 'Statyczny',
    "dictionary_common_module_dynamic" => 'Dynamiczny',
    
    "massage_activate" => "Pomyślnie aktywowano wpis",
    "massage_deactivate" => "Pomyślnie deaktywowano wpis",
    "massage_deleted" => "Pomyślnie usunięto wpis",
    "massage_positions" => "Pomyślnie zaktualizowano pozycje",
    "massage_configuration_modified" => "Pomyślnie zmodyfikowano konfigurację",
    "massage_menu_add_error" => "Błąd podczas dodawania menu",
    "massage_menu_added" => "Pomyślnie dodano menu",
    "massage_menu_modified" => "Pomyślnie zmodyfikowano menu",
    "massage_menu_unique_symbol_error" => "Podany symbol istnieje w bazie danych",
    "massage_menu_unique_url_error" => "Podany url istnieje w bazie danych",
    "massage_menu_manage_submit" => "Dodano moduł do elementu menu",
    "massage_menu_manage_delete" => "Usunięto moduł z elementu menu",
    "massage_modules_added" => "Pomyślnie dodano moduł",
    "massage_modules_modified" => "Pomyślnie zmodyfikowano moduł",
    "massage_modules_unique_file_error" => "Plik o podanej nazwie isnieje w bazie danych",
    "massage_users_add_error" => "Błąd podczas dodawania użytkownika",
    "massage_users_added" => "Pomyślnie dodano użytkownika",
    "massage_users_modified" => "Pomyślnie zmodyfikowano użytkownika",
    "massage_users_unique_login_error" => "Użytkownik o podamym loginie isnieje w bazie danych",
    "massage_partials_added" => "Pomyślnie dodano pojedynczy element",
    "massage_partials_add_error" => "Błąd podczas dodawania pojedynczego elementu",
    "massage_partials_edit_error" => "Błąd podczas edytowania pojedynczego elementu",
    "massage_partials_unique_symbol_error" => "Podany symbol istnieje w bazie danych",
    "massage_partials_empty_name_error" => 'Poste lub błędne pole "Nazwa"',
    "massage_security_refferer_error" => "Błędny reqest refferer",
    "massage_security_token_error" => "Błędny lub pusty reqest token",
    "massage_security_access_error" => "Nie masz dostępu do wybranego elementu",
    "massage_login_error" => "Błędny login lub hasło",
    "massage_login_active_error" => "Konto jest nieaktywne",
    
    "alert_perform_this_action" => "Czy na pewno chcesz wykonać tą akcję?",
    "alert_title_delete_module" => "Usunięcie modułu: ",
    "alert_title_delete_emelent" => "Usuń element",
]

?>